wiki/encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"

urlpatterns = [
    path("", views.index, name="index"),
    path("<str:name>", views.view, name="view")
]

wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

wiki/encyclopedia/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import HttpResponseRedirect

from . import util


def index(request):
    if request.method == 'POST':
        searchValue = request.POST['q'].strip()
        for iten in util.list_entries():
            if searchValue.lower() == iten.lower():
                return HttpResponseRedirect(reverse('encyclopedia:view', args = [iten]))
            
        entries =[]
        for iten in util.list_entries():
            if searchValue.lower() in iten.lower():
                entries += [iten]

        return render(request, "encyclopedia/results.html",{
            'entries':entries,
            'searchValue': searchValue
        })

        
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def view(request, name):
    view = util.get_entry(f"{name}")

    if view == None:
        return render(request, "encyclopedia/error.html", {
            "title":name
        })
    return render(request, "encyclopedia/view.html", {
        "title":name,
        "view":view
    })

wiki/encyclopedia/templates/encyclopedia/error.html
{% extends 'encyclopedia/layout.html' %}
{% block title %}{{title}}{% endblock %}

{% block body %}
{{view}}
<h3>
    A página solicitada: {{title}}<br>
    Não Existe
</h3>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'encyclopedia:view' entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:index' %}" method="post">
                    {% csrf_token %}
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    Create New Page
                </div>
                <div>
                    Random Page
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

wiki/encyclopedia/templates/encyclopedia/results.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Results</h1>

    <ul>{% if entries %}
            {% for entry in entries %}
                <li><a href="{% url 'encyclopedia:view' entry %}">{{ entry }}</a></li>
            {% endfor %}
        {% else %}
            <h3>Nenhum resultado para {{searchValue}} encontrado.</h3>
        {% endif %}
    </ul>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/view.html
{% extends 'encyclopedia/layout.html' %}
{% block title %}{{title}}{% endblock %}

{% block body %}
{{view}}
{% endblock %}